; PlatformIO Project Configuration File
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = ladder_track

[env]
platform = atmelavr
framework = arduino
board = uno
build_flags = -std=gnu++1z
build_unflags = -std=gnu++11

[env:ladder_track]
build_src_filter =
    +<*>
    -<button_test/>
    -<i2c_scan/>
    -<servo_test/>
    -<switch_board/>

[env:servo_test]
lib_deps =
    adafruit/Adafruit PWM Servo Driver Library@^3.0.3

build_src_filter =
    +<*>
    -<button_test/>
    -<i2c_scan/>
    -<ladder_track/>
    -<switch_board/>

[env:button_test]
build_src_filter =
    +<*>
    -<i2c_scan/>
    -<ladder_track/>
    -<servo_test/>
    -<switch_board/>

[env:i2c_scan]
build_src_filter =
    +<*>
    -<button_test/>
    -<ladder_track/>
    -<servo_test/>
    -<switch_board/>

[env:switch_board]
lib_deps =
    adafruit/Adafruit PWM Servo Driver Library@^3.0.3

build_src_filter =
    +<*>
    -<button_test/>
    -<i2c_scan/>
    -<servo_test/>
    -<ladder_track/>
