; PlatformIO Project Configuration File
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = uno_ladder_track

[env]
platform = atmelavr
framework = arduino
board = uno
build_flags = -std=gnu++1z
build_unflags = -std=gnu++11

[env:uno_ladder_track]
build_src_filter =
    +<*>
    -<button_test/>
    -<i2c_scan/>
    -<servo_test/>
    -<switch_board/>

[env:uno_servo_test]
lib_deps =
    adafruit/Adafruit PWM Servo Driver Library@^3.0.3

build_src_filter =
    +<*>
    -<button_test/>
    -<i2c_scan/>
    -<ladder_track/>
    -<switch_board/>

[env:uno_button_test]
build_src_filter =
    +<*>
    -<i2c_scan/>
    -<ladder_track/>
    -<servo_test/>
    -<switch_board/>

[env:uno_i2c_scan]
build_src_filter =
    +<*>
    -<button_test/>
    -<ladder_track/>
    -<servo_test/>
    -<switch_board/>

[env:esp32_poe2_i2c_scan]
platform = espressif32
board = esp32-poe2
framework = arduino
monitor_speed = 115200
build_flags =
    ${env.build_flags}
    -DI2C_SCAN_SDA_PIN=13
    -DI2C_SCAN_SCL_PIN=33
    -DSERIAL_BAUD=115200
build_src_filter =
    +<*>
    -<button_test/>
    -<ladder_track/>
    -<servo_test/>
    -<switch_board/>

[env:uno_switch_board]
lib_deps =
    adafruit/Adafruit PWM Servo Driver Library@^3.0.3

build_src_filter =
    +<*>
    -<button_test/>
    -<i2c_scan/>
    -<servo_test/>
    -<ladder_track/>
