; PlatformIO Project Configuration File
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = ladder_track

[env]
platform = atmelavr
framework = arduino
board = uno
build_flags = -std=gnu++1z
build_unflags = -std=gnu++11

[env:ladder_track]
build_src_filter =
    +<*>
    -<servo_test/>

[env:servo_test]
lib_deps =
    adafruit/Adafruit PWM Servo Driver Library@^3.0.3

build_src_filter =
    +<*>
    -<ladder_track/>
